site_name: Drift Wars Editor

nav:
    - 'Starting Location': 'index.md'
    - 'Modes':
      - 'Cliffs/Ramps': 'modes/cliffsRamps.md'
      - 'Height Map': 'modes/heightMap.md'
      - 'Spawns': 'modes/spawns.md'
      - 'Tex Splatting': 'modes/texSplatting.md'
      - 'Units': 'modes/units.md'
      - 'Triangles': 'modes/triangles.md'
      - 'Triangle Groups': 'modes/triangleGroups.md'
      - 'Decals': 'modes/decals.md'
      - 'Unbuildable': 'modes/unbuildable.md'
      - 'Footprints': 'modes/footprints.md'
      - 'Tex Layers': 'modes/texLayers.md'
      - 'Locations': 'modes/locations.md'
    - Other:
      - 'Map Settings': 'other/mapSettings.md'
      - 'Scene Settings': 'other/sceneSettings.md'
      - '[1v1] Spawns': 'other/1v1Spawns.md'
      - '[Teams] Spawns': 'other/teamSpawns.md'
      - 'Data Editor': 'other/dataEditor.md'
      - 'Script': 'other/script.md'
      - '[Custom] Forces': 'other/forces.md'
      - '[Custom] Tags': 'other/tags.md'
      - '[Custom] Tags Per Force': 'other/tagsPerForce.md'
    - 'Side Controls': 'sideControls.md'
    - 'Misc':
      - 'Text Encoding': 'misc/textEncoding.md'
    - 'Drift Script':
        - 'Introduction': 'driftScript/intro.md'
        - 'Script Entry Points': 'driftScript/scriptEntryPoints.md'
        - 'Identifiers': 'driftScript/identifiers.md'
        - 'Built-in Types': 'driftScript/builtinTypes.md'
        - 'Math Library': 'driftScript/math.md'
        - 'Functions': 'driftScript/functions.md'
        - 'Enumerations': 'driftScript/enumerations.md'
        - 'Event Queue': 'driftScript/eventQueue.md'
        - 'VSCode Syntax Highlighting': 'driftScript/vscodeSyntaxHighlighting.md'
        - 'Examples and Gotchyas': 'driftScript/gotchyas.md'
        - 'More Examples..': 'driftScript/examples.md'

theme:
    name: material
    highlightjs: false  # disable highlight.js
    palette:
      # Palette toggle for light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode

      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

plugins:
  - search
  - macros

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true   # enable Pygments highlighting
      guess_lang: false    # prevent guessing
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - sq_lexer